[env:native]
platform = native
framework = arduino
lib_deps =
    bodmer/TFT_eSPI
    throwtheswitch/Unity
build_flags = -D ARDUINO_ARCH_RP2040
test_ignore = test_DisplayClient

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps =
    bodmer/TFT_eSPI
    throwtheswitch/Unity
build_flags = -D ARDUINO_ARCH_ESP32
test_ignore = test_DisplayServer
